### ISSUE TITLE
新手求助

### ISSUE THREAD

**Issue by jyuan15** [wangyi2005/v2ray-heroku#12]
刚接触v2ray，完全不懂怎么弄。看了些教程，部署的APP打开后显示Bad Request，这应该成功了吧。

v2rayN配置如下图，但PAC模式或全局都不能上外网，日志也没有输出信息，请帮忙看看哪里还没对？谢谢

![2018-07-06_183614](https://user-images.githubusercontent.com/12642186/42374953-7b341990-8109-11e8-9e1f-b1db79057ac0.jpg)

**Comment by wangyi2005** [comment]
GUI客户端如何配置我不会啊

**Comment by onplus** [comment]
80    ws
443  ws tls 

![](https://user-images.githubusercontent.com/31188782/33361465-3b90a2a6-d513-11e7-9ddc-adad7ae829ed.png)

**Comment by jyuan15** [comment]
@onplus 终于可以了，非常感谢~

**Comment by shamashii** [comment]
今天tg上某袋里ch发布r主的项目了，感觉可用期限tangent中
