### ISSUE TITLE
今天下午开始貌似不行了，不能用了

### ISSUE THREAD

**Issue by iambonboncat** [wangyi2005/v2ray-heroku#19]
今天下午开始貌似不行了，不能用了

**Comment by iambonboncat** [comment]
2018/08/10 23:34:24 tcp:127.0.0.1:53094 accepted tcp:91.108.56.110:80 
2018/08/10 23:34:24 [Warning] failed to handler mux client connection > Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (ws://bonboncat.herokuapp.com/): 404 Not Found > websocket: bad handshake] > Retry: all retry attempts failed

**Comment by t2015q** [comment]
我也一样，不知道怎么回事。

**Comment by wlywanmei** [comment]
被封号了，heroku的官方回复是违反用户协议，不能用来做代理。

**Comment by whhxmwhh** [comment]
一键部署 v2ray 到 heroku (已经失效，请勿部署)
oo 我是昨晚开始不能用。。但是以前布置 的还能用。就是近期布置的不能用了。

**Comment by whhxmwhh** [comment]
坐等版主再测试了。

**Comment by 9881888** [comment]
我是来看评论的，从昨天清晨就不能用了。

**Comment by 9881888** [comment]
昨天一早就不能用了惨惨惨

**Comment by whhxmwhh** [comment]
估计是github.com，heroku都被“蓝金黄”了。部署别的也是很快就失效。重新启动没反应。blanch

**Comment by tislam8888** [comment]
要怪就怪 有人 把这个项目的东西 公开发到youtube上面做视频介绍

**Comment by rrn21833** [comment]
有些能用，有些不能用了。十有八九系伟光正搞的鬼。

**Comment by xmbhsqktdqfpqdy** [comment]
昨天晚上失效了

**Comment by HamJin** [comment]
旧的也不行了，自动关闭
