### ISSUE TITLE
请推荐个日常用的，谢谢

### ISSUE THREAD

**Issue by devcodewak** [wangyi2005/v2ray-heroku#2]
@wangyi2005 
一直在关注，最近openshift v3 在清理proxy，看你在更新heroku相关，辛苦了

请从你角度，推荐个日常稳定用的，用于openshift v3和heroku等， 比对下各优略，谢谢
gost / gsnova / v2ray ......

**Comment by wangyi2005** [comment]
从客户端、稳定性看，应该用 v2ray吧

**Comment by wangyi2005** [comment]
1、不清楚openshift的代理检查机制，也许改个名称可以规避。
2、v2ray好像没有明确说支持http2，gost、gsnova都可以支持http2的。
3、v2ray有android版 （https://www.v2ray.com/ui_client） ；gsnova也有的，但是没有发布在google play；gost就没有了。

**Comment by devcodewak** [comment]
收到，thx
