### ISSUE TITLE
这个链接可以一键部署

### ISSUE THREAD

**Issue by baymax55** [wangyi2005/v2ray-heroku#20]
https://github.com/gfw-breaker/heroku-node-proxy

**Comment by whhxmwhh** [comment]
是吗？我去试试。好像是her换了go语言平台。我也是不懂代码。

**Comment by whhxmwhh** [comment]
这个是另外的代理方式哦。我要V2RAY

**Comment by whhxmwhh** [comment]
可以作为应急使用了。

**Comment by tislam8888** [comment]
不是V2ray

**Comment by jimoshizhe** [comment]
这个是轮子直接复制别人的项目，使用原作者的（https://github.com/liuxinagxiang/heroku-proxy）安全点

**Comment by gfw-breaker** [comment]
@jimoshizhe 究竟谁是原作者，请你自己看。https://github.com/liuxinagxiang/heroku-proxy/commits/master  
请不要无脑黑， 动不动就”轮子“；开放源代码，安不安全自己看看就知道了；既然会翻墙了，就不要用被灌输形成的那套思维方式去思考问题

**Comment by whhxmwhh** [comment]
管他是谁家的。。只要能部署成功就好。车轮也好方向盘也用。

**Comment by whhxmwhh** [comment]
Internal Server Error。。好像不能用。。还是早期的V2RAY
全代理好用。

**Comment by whhxmwhh** [comment]
网页在线代理。

**Comment by rrn21833** [comment]
还行，缺点是打不开Twitter书签。

**Comment by xiaokaixuan** [comment]
https://github.com/xiaokaixuan/gost-heroku
