### ISSUE TITLE
app访问出现 bad request了

### ISSUE THREAD

**Issue by kirbyzhu** [wangyi2005/v2ray-heroku#3]
但是客户端配置好后无法正常访问

使用自有UUID了

![image](https://user-images.githubusercontent.com/10296293/36602605-602f7c9e-18f3-11e8-9d2c-e71f09b3051a.png)

**Comment by wangyi2005** [comment]
如果用tls，服务器端口是443，vmess加密选“none”。
不用tls，服务器端口是80，vmess加密为“auto”。

**Comment by kirbyzhu** [comment]
可以了，谢谢！
看docker的代码以为ws的端口改成8080了

**Comment by kirbyzhu** [comment]
tls，使用443之后，我发现vmess的加密选择gcm或者chacha这些也可以。不一定要none。

**Comment by wangyi2005** [comment]
没必要双重加密吧

**Comment by kirbyzhu** [comment]
原来如此 对加密这些还是不太了解

**Comment by CruiseAW** [comment]
谢谢，这个原理不清楚，为什么域名PING不通，还能用呢
