### ISSUE TITLE
有没有手动教程啊？或者把websocket换成h2?

### ISSUE THREAD

**Issue by caonimac** [wangyi2005/v2ray-heroku#6]
现在v2支持h2了，想试试速度。

**Comment by wangyi2005** [comment]
The Heroku router only supports HTTP/1.0 and HTTP/1.1 clients. HTTP/0.9 and earlier are no longer supported. SPDY and HTTP/2 are not supported at this point.

**Comment by caonimac** [comment]
哦哦感谢
